apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        namespace: "observability"
    spec:
      containers:
      - name: frontend
        image: chandc/frontend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: "observability"
spec:
    selector:
        app: frontend
    ports:
        - port: 8080
          targetPort: 8080
    type: LoadBalancer